openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts Manager App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Contacts operations

tags:
  - name: Contacts
    description: Operations with contacts

servers:
  - url: http://localhost:3000
  - url: https://hw7-swagger-qzew.onrender.com

paths:
  /contacts:
    get:
      summary: Отримати всі контакти
      operationId: getAllContacts
      responses:
        200:
          description: Список контактів
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Contact"
        500:
          description: Внутрішня помилка сервера

    post:
      summary: Створити новий контакт
      operationId: createContact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - phoneNumber
                - email
                - contactType
              properties:
                name:
                  type: string
                  description: Ім'я контакту
                phoneNumber:
                  type: string
                  description: Номер телефону
                email:
                  type: string
                  description: Email
                contactType:
                  type: string
                  enum: [work, personal, home]
      responses:
        201:
          description: Успішно створено контакт
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"

  /contacts/{id}:
    get:
      summary: Отримати контакт за ID
      operationId: getContactById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "67ca67e7ae7f10c25b566655"
      responses:
        200:
          description: Знайдено контакт
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
        404:
          description: Контакт не знайдено
        500:
          description: Внутрішня помилка сервера

    patch:
      summary: Оновити контакт
      operationId: updateContact
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "67ca67e7ae7f10c25b566655"
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Ім'я контакту
                phoneNumber:
                  type: string
                  description: Номер телефону
                email:
                  type: string
                  description: Email
                contactType:
                  type: string
                  enum: [work, personal, home]
      responses:
        200:
          description: Успішно оновлено контакт
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"

    delete:
      summary: Видалити контакт
      operationId: deleteContact
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Контакт успішно видалено

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    Contact:
      type: object
      properties:
        id:
          type: string
          example: "67ca67e7ae7f10c25b566655"
        name:
          type: string
          example: "Іван Петров"
        phoneNumber:
          type: string
          example: "+380975554532"
        email:
          type: string
          example: "ivanpele@gmail.com"
        contactType:
          type: string
          enum: [work, personal, home]
