openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts Manager App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Contacts operations
servers:
  - url: https://hw7-swagger-qzew.onrender.com
  - url: http://localhost:3000
tags:
  - name: Contacts
    description: Операції з контактами
paths:
  /contacts:
    get:
      tags:
        - Contacts
      summary: Отримати всі контакти
      operationId: getAllContacts
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            example: 1
        - name: perPage
          in: query
          schema:
            type: integer
            example: 10
        - name: sortBy
          in: query
          schema:
            type: string
            example: "name"
        - name: sortOrder
          in: query
          schema:
            type: string
            enum: [asc, desc]
            example: "asc"
        - name: type
          in: query
          description: "Фільтрація за типом контакту"
          schema:
            type: string
            example: "work"
        - name: isFavourite
          in: query
          description: "Фільтрація за позначкою улюбленості (true/false)"
          schema:
            type: string
            example: "true"
      responses:
        '200':
          description: Список контактів
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "Contacts retrieved successfully"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contact'
        '404':
          $ref: '#/components/responses/NotFound'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'
    post:
      tags:
        - Contacts
      summary: Створити новий контакт
      operationId: createContact
      description: "Create a contact with payload"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - name
                - phoneNumber
                - contactType
              properties:
                name:
                  description: "Contact's name"
                  type: string
                  example: "John Doe"
                phoneNumber:
                  description: "Contact's phone number"
                  type: string
                  example: "+380987654321"
                email:
                  description: "Contact's email"
                  type: string
                  example: "JohnDoe123@gmail.com"
                contactType:
                  description: "Contact's contact type"
                  type: string
                  example: "personal"
                isFavourite:
                  description: "Contact's isFavourite"
                  type: boolean
                  example: false
                photo:
                  description: "Contact's photo"
                  type: string
                  format: binary
      responses:
        '201':
          description: "Creates a contact"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessCreatedResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'
  /contacts/{id}:
    get:
      tags:
        - Contacts
      summary: Отримати контакт за ID
      operationId: getContactById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "67ca67e7ae7f10c25b566655"
      responses:
        '200':
          description: "Знайдено контакт"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
    patch:
      tags:
        - Contacts
      summary: Оновити контакт
      operationId: updateContact
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "67ca67e7ae7f10c25b566655"
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  description: "Contact's name"
                  type: string
                phoneNumber:
                  description: "Contact's phone number"
                  type: string
                email:
                  description: "Contact's email"
                  type: string
                contactType:
                  description: "Contact's contact type"
                  type: string
                  enum: [work, personal, home]
                isFavourite:
                  description: "Contact's isFavourite"
                  type: boolean
                photo:
                  description: "Contact's photo"
                  type: string
                  format: binary
      responses:
        '200':
          description: "Successfully patched a contact!"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
        - Contacts
      summary: Видалити контакт
      operationId: deleteContact
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: "Контакт успішно видалено"
        '404':
          $ref: '#/components/responses/NotFound'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Contact:
      type: object
      properties:
        id:
          type: string
          example: "67ca67e7ae7f10c25b566655"
        name:
          type: string
          example: "John Doe"
        phoneNumber:
          type: string
          example: "+380987654321"
        email:
          type: string
          example: "JohnDoe123@gmail.com"
        contactType:
          type: string
          enum: [work, personal, home]
          example: "personal"
        isFavourite:
          type: boolean
          example: false
        photo:
          type: string
          format: binary
          example: ""
        userId:
          type: string
          example: "67bfa7a9925aebdb493b5b33"
    SuccessResponse:
      type: object
      properties:
        status:
          type: integer
          example: 200
        message:
          type: string
          example: "Operation successful"
        data:
          type: object
          $ref: '#/components/schemas/Contact'
    SuccessCreatedResponse:
      type: object
      properties:
        status:
          type: integer
          example: 201
        message:
          type: string
          example: "Successfully created a contact!"
        data:
          type: object
          $ref: '#/components/schemas/Contact'
  responses:
    BadRequest:
      description: "Невірний запит"
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              message:
                type: string
                example: "Bad request"
    Unauthorized:
      description: "Неавторизовано"
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              message:
                type: string
                example: "Unauthorized"
    NotFound:
      description: "Не знайдено"
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 404
              message:
                type: string
                example: "Not found"
    ServerError:
      description: "Внутрішня помилка сервера"
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              message:
                type: string
                example: "Internal Server Error"
